add python script

diff --git a/.pipelines/create-release-branch.yaml b/.pipelines/create-release-branch.yaml
--- a/.pipelines/create-release-branch.yaml
+++ b/.pipelines/create-release-branch.yaml
@@ -24,16 +24,27 @@ jobs:
       - checkout: self
         persistCredentials: true
 
+      - task: UsePythonVersion@0
+        inputs:
+          versionSpec: '3.9.6'
+          addToPath: true
+
       - script: |
-          set -euo pipefail
-          CHART_VERSION=$(awk -F'|' 'NR > 2 && $2 !~ /^[[:spae:]]*-+[[:space:]]*$/ {gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); if ($2 != "") {print $2; exit}}' docs/installation/versions_mapping.md)
-          MAJOR=$(echo "$CHART_VERSION" | cut -d. -f1)
-          MINOR=$(echo "$CHART_VERSION" | cut -d. -f2)
-          NEXT_MINOR=$((MINOR + 1))
-          NEXT_CHART_VERSION="${MAJOR}.${NEXT_MINOR}"
-          echo "Next chart version: $NEXT_CHART_VERSION"
-          echo "##vso[task.setvariable variable=NEXT_CHART_VERSION]$NEXT_CHART_VERSION"
-        displayName: 'Compute next chart version'
+          python -m pip install --upgrade pip
+          pip install azure-devops
+          python .pipelines/scripts/create_release_branch.py $(AZURE_DEVOPS_PAT_RO)
+        displayName: 'Run schedule check'
+       
+      # - script: |
+      #     set -euo pipefail
+      #     CHART_VERSION=$(awk -F'|' 'NR > 2 && $2 !~ /^[[:space:]]*-+[[:space:]]*$/ {gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); if ($2 != "") {print $2; exit}}' docs/installation/versions_mapping.md)
+      #     MAJOR=$(echo "$CHART_VERSION" | cut -d. -f1)
+      #     MINOR=$(echo "$CHART_VERSION" | cut -d. -f2)
+      #     NEXT_MINOR=$((MINOR + 1))
+      #     NEXT_CHART_VERSION="${MAJOR}.${NEXT_MINOR}"
+      #     echo "Next chart version: $NEXT_CHART_VERSION"
+      #     echo "##vso[task.setvariable variable=NEXT_CHART_VERSION]$NEXT_CHART_VERSION"
+      #   displayName: 'Compute next chart version'
 
       # - script: |
       #     git fetch origin main
@@ -42,118 +53,118 @@ jobs:
       #     git checkout -b "releases/$(NEXT_CHART_VERSION)/official"
       #   displayName: 'Create release branch'
 
-      - script: |
-          MESSAGE_PAYLOAD=$(cat <<EOF
-          {
-            "blocks": [
-              {
-                "type": "section",
-                "text": {
-                  "type": "mrkdwn",
-                  "text": "<!here> ⚠️ *Create release branch pipeline failed*"
-                }
-              },
-              {
-                "type": "section",
-                "fields": [
-                  {
-                    "type": "mrkdwn",
-                    "text": "*Pipeline:*\n$BUILD_DEFINITIONNAME"
-                  },
-                  {
-                    "type": "mrkdwn",
-                    "text": "*Triggered By:*\n$BUILD_REQUESTEDFOR"
-                  }
-                ]
-              },
-              {
-                "type": "actions",
-                "elements": [
-                  {
-                    "type": "button",
-                    "text": {
-                      "type": "plain_text",
-                      "text": "View Failed Build",
-                      "emoji": true
-                    },
-                    "url": "$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECT/_build/results?buildId=$BUILD_BUILDID",
-                    "action_id": "view_failed_build",
-                    "style": "danger"
-                  }
-                ]
-              }
-            ]
-          }
-          EOF
-          )
+      # - script: |
+      #     MESSAGE_PAYLOAD=$(cat <<EOF
+      #     {
+      #       "blocks": [
+      #         {
+      #           "type": "section",
+      #           "text": {
+      #             "type": "mrkdwn",
+      #             "text": "<!here> ⚠️ *Create release branch pipeline failed*"
+      #           }
+      #         },
+      #         {
+      #           "type": "section",
+      #           "fields": [
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*Pipeline:*\n$BUILD_DEFINITIONNAME"
+      #             },
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*Triggered By:*\n$BUILD_REQUESTEDFOR"
+      #             }
+      #           ]
+      #         },
+      #         {
+      #           "type": "actions",
+      #           "elements": [
+      #             {
+      #               "type": "button",
+      #               "text": {
+      #                 "type": "plain_text",
+      #                 "text": "View Failed Build",
+      #                 "emoji": true
+      #               },
+      #               "url": "$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECT/_build/results?buildId=$BUILD_BUILDID",
+      #               "action_id": "view_failed_build",
+      #               "style": "danger"
+      #             }
+      #           ]
+      #         }
+      #       ]
+      #     }
+      #     EOF
+      #     )
 
-          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE_PAYLOAD" "$SLACK_WEBHOOK_URL"
-        target:
-          container: host
-        env:
-          SLACK_WEBHOOK_URL: $(DEVOPS_ALERTS_SLACK_WEBHOOK_URL) # devops-alerts
-        condition: failed()
-        continueOnError: true
-        displayName: Report pipeline failures
+      #     curl -X POST -H 'Content-type: application/json' --data "$MESSAGE_PAYLOAD" "$SLACK_WEBHOOK_URL"
+      #   target:
+      #     container: host
+      #   env:
+      #     SLACK_WEBHOOK_URL: $(DEVOPS_ALERTS_SLACK_WEBHOOK_URL) # devops-alerts
+      #   condition: failed()
+      #   continueOnError: true
+      #   displayName: Report pipeline failures
 
-      - script: |
-          MESSAGE_PAYLOAD=$(cat <<EOF
-          {
-            "blocks": [
-              {
-                "type": "section",
-                "text": {
-                  "type": "mrkdwn",
-                  "text": ":tada: *Create release branch pipeline succeeded*"
-                }
-              },
-              {
-                "type": "section",
-                "fields": [
-                  {
-                    "type": "mrkdwn",
-                    "text": "*Pipeline:*\n$BUILD_DEFINITIONNAME"
-                  },
-                  {
-                    "type": "mrkdwn",
-                    "text": "*Triggered By:*\n$BUILD_REQUESTEDFOR"
-                  },
-                  {
-                    "type": "mrkdwn",
-                    "text": "*Next Chart Version:*\n$(NEXT_CHART_VERSION)"
-                  },
-                  {
-                    "type": "mrkdwn",
-                    "text": "*New Branch Name:*\nreleases/$(NEXT_CHART_VERSION)/official"
-                  }
-                ]
-              },
-              {
-                "type": "actions",
-                "elements": [
-                  {
-                    "type": "button",
-                    "text": {
-                      "type": "plain_text",
-                      "text": "View Build",
-                      "emoji": true
-                    },
-                    "url": "$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECT/_build/results?buildId=$BUILD_BUILDID",
-                    "action_id": "view_build",
-                    "style": "primary"
-                  }
-                ]
-              }
-            ]
-          }
-          EOF
-          )
+      # - script: |
+      #     MESSAGE_PAYLOAD=$(cat <<EOF
+      #     {
+      #       "blocks": [
+      #         {
+      #           "type": "section",
+      #           "text": {
+      #             "type": "mrkdwn",
+      #             "text": ":tada: *Create release branch pipeline succeeded*"
+      #           }
+      #         },
+      #         {
+      #           "type": "section",
+      #           "fields": [
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*Pipeline:*\n$BUILD_DEFINITIONNAME"
+      #             },
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*Triggered By:*\n$BUILD_REQUESTEDFOR"
+      #             },
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*Next Chart Version:*\n$(NEXT_CHART_VERSION)"
+      #             },
+      #             {
+      #               "type": "mrkdwn",
+      #               "text": "*New Branch Name:*\nreleases/$(NEXT_CHART_VERSION)/official"
+      #             }
+      #           ]
+      #         },
+      #         {
+      #           "type": "actions",
+      #           "elements": [
+      #             {
+      #               "type": "button",
+      #               "text": {
+      #                 "type": "plain_text",
+      #                 "text": "View Build",
+      #                 "emoji": true
+      #               },
+      #               "url": "$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECT/_build/results?buildId=$BUILD_BUILDID",
+      #               "action_id": "view_build",
+      #               "style": "primary"
+      #             }
+      #           ]
+      #         }
+      #       ]
+      #     }
+      #     EOF
+      #     )
 
-          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE_PAYLOAD" "$SLACK_WEBHOOK_URL"
-        target:
-          container: host
-        env:
-          SLACK_WEBHOOK_URL: $(DEVOPS_PERIODIC_ALERTS_SLACK_WEBHOOK_URL) # devops-periodic-alerts
-        condition: succeeded()
-        continueOnError: true
-        displayName: Report pipeline success
+      #     curl -X POST -H 'Content-type: application/json' --data "$MESSAGE_PAYLOAD" "$SLACK_WEBHOOK_URL"
+      #   target:
+      #     container: host
+      #   env:
+      #     SLACK_WEBHOOK_URL: $(DEVOPS_PERIODIC_ALERTS_SLACK_WEBHOOK_URL) # devops-periodic-alerts
+      #   condition: succeeded()
+      #   continueOnError: true
+      #   displayName: Report pipeline success
